### ISSUE TITLE
Darkuś zyebałeś

### ISSUE THREAD

**Issue by PanCzerwonySer** [PanCzerwonySer/DogOS-WP#44]
Running: gcc -m32 -c src/Modules/vga.c -o build/vga.o -std=gnu99 -O2 -Wall -Wextra -fno-builtin -nostdlib
In file included from src/Modules/vga.c:2:0:
src/Modules/definitions.h:10:24: error: conflicting types for ‘uint16_t’
 typedef unsigned short uint16_t;
                        ^~~~~~~~
In file included from src/Modules/vga.c:1:0:
src/Modules/vga.h:4:22: note: previous declaration of ‘uint16_t’ was here
 typedef unsigned int uint16_t;
                      ^~~~~~~~
src/Modules/vga.c:38:6: error: conflicting types for ‘color’
 void color(uint16_t color) {
      ^~~~~
In file included from src/Modules/vga.c:1:0:
src/Modules/vga.h:9:6: note: previous declaration of ‘color’ was here
 void color(uint16_t color);
      ^~~~~
Running: gcc -m32 -c src/kernel.c -o build/kernel.o -std=gnu99 -O2 -Wall -Wextra -fno-builtin -nostdlib
Running: gcc -m32 -c src/Modules/lib.c -o build/lib.o -std=gnu99 -O2 -Wall -Wextra -fno-builtin -nostdlib
src/Modules/lib.c: In function ‘memcmp’:
src/Modules/lib.c:23:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i<size; i++) {
                         ^
src/Modules/lib.c: In function ‘memcpy’:
src/Modules/lib.c:35:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i<block_size; i++) {
                         ^
Running: gcc -m32 -c src/Modules/keyboard.c -o build/keyboard.o -std=gnu99 -O2 -Wall -Wextra -fno-builtin -nostdlib
src/Modules/keyboard.c: In function ‘getStringn’:
src/Modules/keyboard.c:45:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 1; i<=size+1; i++) {
                         ^~
src/Modules/keyboard.c:49:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if(i<size+1) string[i-1] = getchar();
                 ^
src/Modules/keyboard.c: In function ‘getStringc’:
src/Modules/keyboard.c:64:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int j = 0; j<size; j++) string[j] = temp[j];
                         ^
src/Modules/keyboard.c: In function ‘getStringnp’:
src/Modules/keyboard.c:79:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i<ptr_size-1; i++) {
                         ^
src/Modules/keyboard.c: In function ‘getStringcp’:
src/Modules/keyboard.c:89:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i<ptr_size-1; i++) {
                         ^
src/Modules/keyboard.c: In function ‘strcmp’:
src/Modules/keyboard.c:117:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i<size_a; i++) {
                     ^
src/Modules/keyboard.c: In function ‘getStringn’:
src/Modules/keyboard.c:44:15: warning: ‘string’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         char* string;
               ^~~~~~
Running: ld -m elf_i386 build/boot.o build/kernel.o build/vga.o build/keyboard.o build/io.o build/lib.o -T linker.ld -o kernel -O2 -nostdlib
build/keyboard.o: In function `getStringn':
keyboard.c:(.text+0xa6): undefined reference to `malloc'
keyboard.c:(.text+0xfe): undefined reference to `free'
keyboard.c:(.text+0x110): undefined reference to `malloc'
build/keyboard.o: In function `getStringc':
keyboard.c:(.text+0x1a7): undefined reference to `malloc'
keyboard.c:(.text+0x1fb): undefined reference to `free'

**Comment by Firstbober** [comment]
Zakomentuj funkcje używające malloc i free

**Comment by Dark565** [comment]
no

**Comment by PanCzerwonySer** [comment]
nook

**Comment by PanCzerwonySer** [comment]
problem jest taki

**Comment by PanCzerwonySer** [comment]
że to funkcje darka

**Comment by Dark565** [comment]
Ej

**Comment by Dark565** [comment]
Moje funkcje nie robią problemów

**Comment by Dark565** [comment]
Zauważ, że większość to warningi

**Comment by Dark565** [comment]
warningi, że porównuję unsigned z signed, ale to błędów nie robi

**Comment by Dark565** [comment]
Więc moje funkcje są legit

**Comment by Dark565** [comment]
Nie rozumiem tylko błędu z tymi definicjami

**Comment by Firstbober** [comment]
Malloc mean

**Comment by PanCzerwonySer** [comment]
A wyżej to co?

**Comment by Dark565** [comment]
które wyżej

**Comment by Dark565** [comment]
to z typedef?

**Comment by PanCzerwonySer** [comment]
a nie, to moje xDD

**Comment by Firstbober** [comment]
moje

**Comment by Dark565** [comment]
aha

**Comment by Dark565** [comment]
typedefy konfliktują z jakimś z vga.h
To bober zjebał a nie ja

**Comment by Firstbober** [comment]
xd

**Comment by Dark565** [comment]
Kto tam wsadzał typedefy?

**Comment by Dark565** [comment]
A wy mówicie, że ja zjebałem

**Comment by PanCzerwonySer** [comment]
Na samym dole są twoje funkcje

**Comment by PanCzerwonySer** [comment]
`
build/keyboard.o: In function `getStringn':
keyboard.c:(.text+0xa6): undefined reference to `malloc'
keyboard.c:(.text+0xfe): undefined reference to `free'
keyboard.c:(.text+0x110): undefined reference to `malloc'
build/keyboard.o: In function `getStringc':
keyboard.c:(.text+0x1a7): undefined reference to `malloc'
keyboard.c:(.text+0x1fb): undefined reference to `free'

`

**Comment by Dark565** [comment]
Wiem
Ale to tylko warningi

**Comment by PanCzerwonySer** [comment]
no fajnie to wygląda githubie

**Comment by Dark565** [comment]
No, bo malloc

**Comment by PanCzerwonySer** [comment]
jakie warningi xDD

**Comment by Dark565** [comment]
wysłałem pulle z #includami zaakceptuj

**Comment by Dark565** [comment]
nie miałeś includa z mallociem

**Comment by Dark565** [comment]
dlatego errory

**Comment by PanCzerwonySer** [comment]
30 komentarzy xDD

**Comment by Dark565** [comment]
no i tak. malloc i free nie ma wnętrza

**Comment by Firstbober** [comment]
ja mam include

**Comment by Firstbober** [comment]
src/Modules/lib.c: In function ‘memcmp’:
src/Modules/lib.c:23:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i<size; i++) {
                         ^
src/Modules/lib.c: In function ‘memcpy’:
src/Modules/lib.c:35:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i<block_size; i++) {
                         ^
Running: gcc -m32 -c src/Modules/keyboard.c -o build/keyboard.o -std=gnu99 -O2 -Wall -Wextra -fno-builtin -nostdlib
src/Modules/keyboard.c: In function ‘getStringnp’:
src/Modules/keyboard.c:76:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i<ptr_size-1; i++) {
                         ^
src/Modules/keyboard.c: In function ‘strcmp’:
src/Modules/keyboard.c:116:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i<size_a; i++) {

**Comment by Dark565** [comment]
Czekaj dam pulla

**Comment by Dark565** [comment]
To tylko warningi

**Comment by Firstbober** [comment]
zakomentowałem funkcję z malloc

**Comment by Dark565** [comment]
Te warningi tylko dupę zawracają. O nic złym nie mówią

**Comment by Dark565** [comment]
Zrobić aby ich nie było?

**Comment by Firstbober** [comment]
postaraj się
ja się teraz zajmuję getchar
Issue do zamknięcia @PanCzerwonySer

**Comment by PanCzerwonySer** [comment]
Dobra, już wszystkie pull requesty zaakceptowane. Zamykam ten issue.
