### ISSUE TITLE
Darkuś zyebałeś x3

### ISSUE THREAD

**Issue by PanCzerwonySer** [PanCzerwonySer/DogOS-WP#54]
W ogóle, to zapomniałem powiedzieć, że ten tsleep nie działa i w ogóle, weź to napraw czy coś

**Comment by Firstbober** [comment]
xdd

**Comment by Dark565** [comment]
Ok

**Comment by Dark565** [comment]
I nie zjebałem, tylko nie dokonczyłem

**Comment by PanCzerwonySer** [comment]
pewnie zaraz będzie `Darkuś zyebałeś x4` xDD
